### ISSUE TITLE
Alternate streaming scheme

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-milagro-crypto#11]
In Shasper spec, validators will have a `bls_proof_of_possession` see https://github.com/ethereum/eth2.0-specs/blob/master/specs/casper_sharding_v2.1.md#pow-main-chain-changes and https://github.com/ethereum/eth2.0-specs/blob/master/specs/casper_sharding_v2.1.md#routine-for-adding-a-validator

This means that we do not need to build a big sequence of validator keys and then sort, we can directly loop other the validators sequence.

Actually it's probably require to sign in that order.

**Comment by cheatfate** [comment]
@mratsim i have already made it, this type of sorting.

**Comment by mratsim** [comment]
closed by https://github.com/status-im/nim-milagro-crypto/commit/5164e10c465bad00c465556082bf0983a956a5f1
