### ISSUE TITLE
Use uint64 (or uint128) on 64-bit machine

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-milagro-crypto#5]
For quick cross-platform development and 32/64-bit compat, the default is to use `uint32` for everything.

In production we can expect x2 speed with uint64. This is defined by `CHUNKS`

https://github.com/status-im/nim-milagro-crypto/blob/master/src/milagro_crypto/generated/arch.h#L42-L46

**Comment by cheatfate** [comment]
Done
